### ISSUE TITLE
Thank you very much for sharing these codes. Very helpful. I am running it on Google Colab and it works OK on 45 degree fundus photographs.

### ISSUE THREAD

**Issue by rmaphoh** [rmaphoh/AutoMorph#2]
Thank you very much for sharing these codes. Very helpful. I am running it on Google Colab and it works OK on 45 degree fundus photographs. 

I know you would not recommend using it on ultra-wide field images (Optos), but I would love to see how it performance on them. Would the input be the RGB image or channels need to be split and green fed in?

 Also, in terms of the output csvs, I noticed that  Disc_Zone_B_Measurement.csv has exact same values as Disc_Zone_C_Measurement.csv in 'Results\M3\Disc_centred\' directory.  Can I fix that somehow?

_Originally posted by @lajos-cs in https://github.com/rmaphoh/AutoMorph/issues/1#issuecomment-1243015406_

**Comment by rmaphoh** [comment]
For testing on Optos, the input should be RGB. I might suggest avoiding preprocessing and quality grading as those are tailored for CFP in normal field of view.

Thanks for pointing it out. I have revised the code so to rectify the csvs.

**Comment by lajos-cs** [comment]
Hello, 
I was wondering if it was possible to add an extra column to the output files with the laterality of the eye (whether it is right or left eye)? That would be very handy when you have a big batch of images to feed in and you do not have the information in the file name and no resources to manually classify the images.

**Comment by rmaphoh** [comment]
Thanks. This could be added later this year when we start updating the program.
