### ISSUE TITLE
not enough values to unpack in tortuosity_measures.evaluate_window

### ISSUE THREAD

**Issue by smessica** [rmaphoh/AutoMorph#3]
Hi, 
first of all, I really appreciate your work. 
In the M3_feature_zone/retipy/create_datasets.py, you expect the function - tortuosity_measures.evaluate_window will return 15 values, but it only produces 13 values. Is it supposed to be like that? What am I missing?

Thanks, 
Shvat

**Comment by rmaphoh** [comment]
Sorry for the late reply and thanks for your interest in this work.

There are certain scripts that haven't been used and updated in the whole pipeline, e.g., the create_datasets.py you referred to. You can check the run.sh file to see which scripts are used in the calculation. BTW, we will clean the unnecessary files (heavily existing in M3 steps) later this year to make it concise.
