### ISSUE TITLE
Some questions about resolution_information

### ISSUE THREAD

**Issue by daidaidaluannan** [rmaphoh/AutoMorph#5]
I am very grateful that your program has been a great help to our work. The fundus imaging device we use has a resolution of 6 nm, but after I change the resolution information in **resolution_information.csv**, it seems to have no effect on the feature measurement results.

**Comment by rmaphoh** [comment]
Glad to know that AutoMorph can contribute to your work. The resolution will only influence some features (with unit of nm or um), such as vessel width, optic disc/cup height and width, and other calibre metrics. For some ratio-based features, such as tortuosity and fractal dimension, they will be the same.

**Comment by daidaidaluannan** [comment]
Thank you very much for your response! If my resolution is 6 microns, does it mean that I just need to set the 'res' column in the 'resolution_information.csv' file to 6?(Please forgive me for referring to the resolution as 6nm in my previous question)

**Comment by rmaphoh** [comment]
Yep, but I assume that should be 0.006 (For Topcon it is about 0.008).

**Comment by daidaidaluannan** [comment]
Thanks again for your reply！
